version: "3.4"
services:
  db:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test-api
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - webnet
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5454:5454/tcp
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mydomain.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_LISTEN_PORT=5454
    networks:
      - webnet
  # APP*****************************************
  rest-api:
    build: .
    container_name: rest-api
    networks:
      - webnet
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  db:
networks:
  webnet: