version: "3.4"
services:
  db:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test-api
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5454:5454/tcp
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mydomain.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_LISTEN_PORT=5454
  # APP*****************************************
  springbootapp:
    build: .
    container_name: rest-api
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  postgres-data: